using Azure.AI.OpenAI;
using Azure.Identity;
using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;
using OpenAI.Chat;
using ChatMessage = Microsoft.Extensions.AI.ChatMessage;

#pragma warning disable MEAI001 // Acknowledge experimental AI framework features

Console.WriteLine("--- Initializing Remote Mentorship Swarm ---");

// 1. Define the Hosted MCP Tool with Governance
// We connect to the remote SSE endpoint and explicitly demand human approval before execution.
var mcpHostedTool = new HostedMcpServerTool(
    serverName: "microsoft_learn",
    serverAddress: "https://learn.microsoft.com/api/mcp")
{
    // Restrict the agent to only use the search tool
    AllowedTools = ["microsoft_docs_search"],
    // GOVERNANCE: Force the agent to pause and ask permission before crossing the network boundary
    ApprovalMode = HostedMcpServerToolApprovalMode.AlwaysRequire
};

// 2. Initialize the Agent
string endpoint = "https://agents-on-foundry-resource.services.ai.azure.com/";
string deploymentName = "gpt-5-mini";

AIAgent mentorAgent = new AzureOpenAIClient(new Uri(endpoint), new AzureCliCredential())
    .GetChatClient(deploymentName)
    .AsAIAgent(
        name: "ArchitectureMentor",
        instructions: "You answer highly technical .NET questions. You MUST use the 'microsoft_learn' tool to search the official documentation before answering. Always cite your sources.",
        tools: [mcpHostedTool]
    );

// 3. Begin the Stateful Session
AgentSession session = await mentorAgent.CreateSessionAsync();
string prompt = "What are the exact C# classes required to implement the Agent-to-Agent (A2A) protocol in the Microsoft Agent Framework?";
Console.WriteLine($"\nJunior Dev: {prompt}\n");

// 4. Initial Execution (The agent realizes it needs to search and pauses)
AgentResponse response = await mentorAgent.RunAsync(prompt, session);

// Extract any pending approval requests generated by the agent
List<McpServerToolApprovalRequestContent> approvalRequests = response.Messages
    .SelectMany(m => m.Contents)
    .OfType<McpServerToolApprovalRequestContent>()
    .ToList();

// 5. The Governance Loop (Human-in-the-Loop)
while (approvalRequests.Count > 0)
{
    foreach (var request in approvalRequests)
    {
        // Present the agent's intent to the human manager
        Console.WriteLine("\n[SECURITY AUDIT] The agent is attempting to execute a remote tool.");
        Console.WriteLine($"Target Server: {request.ToolCall.ServerName}");
        Console.WriteLine($"Target Tool:   {request.ToolCall.ToolName}");

        string toolArgs = string.Join(", ", request.ToolCall.Arguments?.Select(x => $"{x.Key}: '{x.Value}'") ?? []);
        Console.WriteLine($"Arguments:     {toolArgs}");

        Console.Write("\nApprove network request? (Y/N): ");
        bool isApproved = Console.ReadLine()?.Equals("Y", StringComparison.OrdinalIgnoreCase) ?? false;

        // Package the human's decision back into a ChatMessage
        var approvalMessage = new ChatMessage(ChatRole.User, [request.CreateResponse(isApproved)]);

        // Push the human's approval (or denial) back to the agent and resume execution
        Console.WriteLine("\n[System] Resuming agent execution...");
        response = await mentorAgent.RunAsync(approvalMessage, session);
    }

    // Check if the agent wants to execute *another* tool based on the new results
    approvalRequests = response.Messages
        .SelectMany(m => m.Contents)
        .OfType<McpServerToolApprovalRequestContent>()
        .ToList();
}

// 6. Final Synthesis
Console.WriteLine($"\nSenior Mentor:\n{response.Text}");